image: golang:1.15

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "us-west-2"

build:
  stage: build
  script:
    - GOOS=linux go build -o bin/Authentication Functions/Authentication/main.go
    - GOOS=linux go build -o bin/Main Functions/Modules/main.go
  artifacts:
    expire_in: 5 mins
    paths:
      - bin
      - serverless.yml

deploy:
  image: centos:8
  stage: deploy
  script:
    - yum update -y && yum upgrade -y
    - curl -sL https://rpm.nodesource.com/setup_15.x | bash -
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - yum update -y && yum upgrade -y
    - yum install -y nodejs
    - npm install serverless -g
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
    - serverless deploy --stage ${CI_COMMIT_REF_NAME} --region ${AWS_DEFAULT_REGION}
  except:
    - /^feature\/.*$/
    - /^hotfix\/.*$/